version: '3'
services:
  percona:
    image: percona:latest
    env_file: configuration.env
    ports:
      - '3306:3306'
    volumes:
      - percona_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

  postgres:
    image: postgres:latest
    env_file: configuration.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  percona_data:
  postgres_data: