-- PostgreSQL
CREATE TABLE IF NOT EXISTS wallet (
    id SERIAL PRIMARY KEY,
    balance INT
);

INSERT INTO wallet (balance) VALUES (CAST(FLOOR(RANDOM() * 10000) AS INT));
INSERT INTO wallet (balance) VALUES (CAST(FLOOR(RANDOM() * 10000) AS INT));
INSERT INTO wallet (balance) VALUES (CAST(FLOOR(RANDOM() * 10000) AS INT));
INSERT INTO wallet (balance) VALUES (CAST(FLOOR(RANDOM() * 10000) AS INT));
INSERT INTO wallet (balance) VALUES (CAST(FLOOR(RANDOM() * 10000) AS INT));
